services:
  Chatapp.Shared.QueryHandlers:
    class: ../../../../../Contexts/Shared/infrastructure/QueryBus/QueryHandlers
    arguments: ['!tagged queryHandler']

  Chatapp.Shared.domain.ConversationsService:
    class: ../../../../../Contexts/Shared/infrastructure/QueryBus/InMemoryQueryBus
    arguments: ['@Chatapp.Shared.QueryHandlers']

  Chatapp.Shared.MongoConfig:
    factory:
      class: ../../../../../Contexts/Chatapp/Conversations/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  Chatapp.Shared.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['chatapp', '@Chatapp.Shared.MongoConfig']
