services:
  Chatapp.Shared.QueryHandlers:
    class: ../../../../../Contexts/Shared/infrastructure/QueryBus/QueryHandlers
    arguments: ['!tagged queryHandler']

  Chatapp.Shared.domain.ConversationsService:
    class: ../../../../../Contexts/Shared/infrastructure/QueryBus/InMemoryQueryBus
    arguments: ['@Chatapp.Shared.QueryHandlers']

  Chatapp.Shared.MongoConfig:
    factory:
      class: ../../../../../Contexts/Chatapp/Conversations/infrastructure/persistence/mongo/MongoConfigFactory
      method: 'createConfig'

  Chatapp.Shared.ConnectionManager:
    factory:
      class: ../../../../../Contexts/Shared/infrastructure/persistence/mongo/MongoClientFactory
      method: 'createClient'
    arguments: ['chatapp', '@Chatapp.Shared.MongoConfig']

  Chatapp.Shared.domain.CommandBus:
    class: ../../../../../Contexts/Shared/infrastructure/CommandBus/InMemoryCommandBus
    arguments: ['@Chatapp.Shared.CommandHandlers']

  Chatapp.Shared.CommandHandlers:
    class: ../../../../../Contexts/Shared/infrastructure/CommandBus/CommandHandlers
    arguments: ['!tagged commandHandler']

  Chatapp.Shared.domain.EventBus:
    factory:
      class: ../../../../../Contexts/Chatapp/Shared/infrastructure/RabbitMQ/RabbitMQEventBusFactory
      method: 'create'
    arguments:
      [
        '@Chatapp.Shared.DomainEventFailoverPublisher',
        '@Chatapp.Shared.RabbitMQConnection',
        '@Chatapp.Shared.RabbitMQqueueFormatter',
        '@Chatapp.Shared.RabbitMQConfig',
      ]

  Chatapp.Shared.RabbitMQQueueFormatter:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQqueueFormatter
    arguments: ['chatapp']

  Chatapp.Shared.RabbitMQConnection:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMqConnection
    arguments: ['@Chatapp.Shared.RabbitMQConfig']

  Chatapp.Shared.RabbitMQqueueFormatter:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/RabbitMQ/RabbitMQqueueFormatter
    arguments: ['chatapp']

  Chatapp.Shared.DomainEventFailoverPublisher:
    class: ../../../../../Contexts/Shared/infrastructure/EventBus/DomainEventFailoverPublisher/DomainEventFailoverPublisher
    arguments: ['@Chatapp.Shared.ConnectionManager']

  Chatapp.Shared.RabbitMQConfig:
    factory:
      class: ../../../../../Contexts/Chatapp/Shared/infrastructure/RabbitMQ/RabbitMQConfigFactory
      method: 'createConfig'
