services:
  Apps.Chatapp.Backend.controllers.StatusGetController:
    class: ../../controllers/StatusGetController
    arguments: []

  Apps.Chatapp.Backend.controllers.MessagesPostController:
    class: ../../controllers/MessagesPostController
    arguments: ['@Chatapp.Shared.domain.CommandBus']

  Apps.Chatapp.Backend.controllers.MessagesGetController:
    class: ../../controllers/ConversationsGetController
    arguments: ['@Chatapp.Shared.domain.MessagesService']

  Apps.Chatapp.Backend.controllers.ConversationsGetController:
    class: ../../controllers/ConversationsGetController
    arguments: ['@Chatapp.Shared.domain.ConversationsService']

  Apps.Chatapp.Backend.controllers.ConversationsPostController:
    class: ../../controllers/ConversationsPostController
    arguments: ['@Chatapp.Shared.domain.CommandBus']
